### PR TITLE
resol cs2 and cs4 optimizer added

### PR DESCRIPTION
**Pull request by SurfGargano**

### CODE REVIEW

**Comment by danielwippermann** [comment]
Hi @SurfGargano,

thanks for your pull request. According to the error message from the TravisCI two files are missing. Could you please add them?

Thanks in advance,
Daniel

**Comment by SurfGargano** [comment]
Sorry , had frogotten to add in GIT

**Comment by danielwippermann** [comment]
Thanks for your contribution, I really appreciate it. Would you mind if I add your GitHub username to the list of contributors in the README?

**Comment by SurfGargano** [comment]
Yes, adding to the list of contributors is appreciated.

 

Von: danielwippermann [mailto:notifications@github.com] 
Gesendet: Dienstag, 9. Februar 2021 21:30
An: danielwippermann/resol-vbus <resol-vbus@noreply.github.com>
Cc: Gargano <werner.dungs@dusotec.de>; Mention <mention@noreply.github.com>
Betreff: Re: [danielwippermann/resol-vbus] resol cs2 and cs4 optimizer added (#53)

 

Thanks for your contribution, I really appreciate it. Would you mind if I add your GitHub username to the list of contributors in the README?

**Pull request merged**
